version: "3.7"

networks:
  mngmt:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

services:
  jofisaes_advanced_library_mngmt_postgres:
    hostname: jofisaes_advanced_library_mngmt_postgres
    container_name: jofisaes_advanced_library_mngmt_postgres
    build:
      context: ./docker-psql/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=alm
    ports:
      - "5432:5432"
    networks:
      mngmt:
        ipv4_address: ${POSTGRES_IP}

  jofisaes_advanced_library_mngmt_gate:
    hostname: jofisaes_advanced_library_mngmt_gate
    container_name: jofisaes_advanced_library_mngmt_gate
    build:
      context: advanced-library-mngmt-gate/.
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - jofisaes_advanced_library_mngmt_postgres
    networks:
      mngmt:
        ipv4_address: ${ALM_GATE_IP}

  jofisaes_advanced_library_mngmt_reactive:
    hostname: jofisaes_advanced_library_mngmt_reactive
    container_name: jofisaes_advanced_library_mngmt_reactive
    build:
      context: advanced-library-mngmt-reactive/.
    env_file:
      - .env
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - jofisaes_advanced_library_mngmt_postgres
    networks:
      mngmt:
        ipv4_address: ${ALM_REACTIVE_IP}

  jofisaes_advanced_library_mngmt_mvc:
    hostname: jofisaes_advanced_library_mngmt_mvc
    container_name: jofisaes_advanced_library_mngmt_mvc
    build:
      context: advanced-library-mngmt-mvc/.
    ports:
      - "8082:8082"
    restart: on-failure
    depends_on:
      - jofisaes_advanced_library_mngmt_postgres
    networks:
      mngmt:
        ipv4_address: ${ALM_MVC_IP}

